# Generated by Django 3.0.5 on 2020-04-27 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_one', models.CharField(max_length=50)),
                ('line_two', models.CharField(max_length=100)),
                ('line_three', models.CharField(max_length=100)),
                ('line_four', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='media')),
            ],
        ),
    ]
