# Generated by Django 3.0.5 on 2020-04-27 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartHome', '0007_service_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Other_Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('icon', models.CharField(max_length=50)),
            ],
        ),
    ]
