# Generated by Django 3.0.5 on 2020-04-27 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartHome', '0008_other_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='media')),
                ('image', models.ImageField(upload_to='media')),
                ('description', models.CharField(max_length=200)),
                ('link_facebook', models.CharField(max_length=200)),
                ('link_instagram', models.CharField(max_length=200)),
                ('adress', models.CharField(max_length=100)),
                ('tel_one', models.CharField(max_length=50)),
                ('tel_two', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('copyright_text', models.CharField(max_length=50)),
            ],
        ),
    ]
