# Generated by Django 3.0.5 on 2020-04-28 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartHome', '0009_footer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service_info',
            name='service',
        ),
        migrations.AddField(
            model_name='service_info',
            name='service_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
