# Generated by Django 3.0.5 on 2020-04-28 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartHome', '0010_auto_20200428_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_one', models.CharField(max_length=50)),
                ('line_one', models.CharField(max_length=200)),
                ('header_two', models.CharField(max_length=50)),
                ('line_two', models.CharField(max_length=200)),
                ('iframe', models.CharField(max_length=3000)),
            ],
        ),
    ]
