# Generated by Django 3.0.5 on 2020-04-28 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartHome', '0013_auto_20200428_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='Side_Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
            ],
        ),
    ]
