# Generated by Django 3.0.5 on 2020-04-28 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartHome', '0014_side_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='side_menu',
            name='text',
            field=models.CharField(max_length=500),
        ),
    ]
